keycloak:
  realm: Biobank
  auth-server-url: http://localhost:8180/auth
  resource: sample
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-sample]
      securityCollections:
        - name: Sample private API's
          patterns: ['/sample/*']

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: administrator
      initialization-mode: always

server:
  port: 9092

app:
  shipment = http://localhost:9091
  biobank = http://localhost:9093
  donor = http://localhost:9095