keycloak:
  realm: Biobank
  auth-server-url: http://localhost:8180/auth
  resource: sample
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-sample]
      securityCollections:
        - name: Sample private API's
          patterns: ['/sample/*']

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
      url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: administrator
      initialization-mode: always

server:
  port: 9092

app:
  shipmentService: http://${SHIPMENT_HOST}:9092
  biobankService: http://${BIOBANK_HOST}:9093
  donorService: http://${DONOR_HOST}:9095